/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker-env.d.ts` (hash: fa84ba9c0a9acb85d051092471a9c722)
interface __BaseEnv_WorkerEnv {
	CACHE: KVNamespace;
	DB: D1Database;
	CORS_ORIGIN: string;
	LOG_RETENTION_DAYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CORS_ORIGIN" | "LOG_RETENTION_DAYS">> {}
}
