/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker-env.d.ts` (hash: a844588e805253879d5401d690e691fe)
interface __BaseEnv_WorkerEnv {
	CACHE: KVNamespace;
	DB: D1Database;
	EMAIL_FROM: string;
	CORS_ORIGIN: string;
	LOG_RETENTION_DAYS: string;
	RESEND_API_KEY: string;
	EMAIL_CODE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "CORS_ORIGIN" | "LOG_RETENTION_DAYS" | "RESEND_API_KEY" | "EMAIL_CODE_SECRET">> {}
}
