/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker-env.d.ts` (hash: 49009c5bfdd41a0dcecc837503fdad5a)
interface __BaseEnv_WorkerEnv {
	CACHE: KVNamespace;
	DB: D1Database;
	CORS_ORIGIN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
